/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.3.v201507280808.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef MATH_SUM_sum_if_PROXY_BASE_HPP_
#define MATH_SUM_sum_if_PROXY_BASE_HPP_

#include <v1_0/math/sum/sum_if.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <vector>

#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1_0 {
namespace math {
namespace sum {

class sum_ifProxyBase
    : virtual public CommonAPI::Proxy {
public:

    typedef std::function<void(const CommonAPI::CallStatus&, const double&)> Add2AsyncCallback;



    virtual void add2(const double &_num1, const double &_num2, CommonAPI::CallStatus &_internalCallStatus, double &_result, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> add2Async(const double &_num1, const double &_num2, Add2AsyncCallback _callback, const CommonAPI::CallInfo *_info = nullptr) = 0;
};

} // namespace sum
} // namespace math
} // namespace v1_0

#endif // MATH_SUM_sum_if_PROXY_BASE_HPP_
