/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.3.v201507280808.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef MATH_SUM_sum_if_PROXY_HPP_
#define MATH_SUM_sum_if_PROXY_HPP_

#include <v1_0/math/sum/sum_ifProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif


#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1_0 {
namespace math {
namespace sum {

template <typename ... _AttributeExtensions>
class sum_ifProxy
    : virtual public sum_if, 
      virtual public sum_ifProxyBase,
      public _AttributeExtensions... {
public:
    sum_ifProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~sum_ifProxy();

    typedef sum_if InterfaceType;




    /**
     * Calls add2 with synchronous semantics.
     * 
    * All const parameters are input parameters to this method.
    * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void add2(const double &_num1, const double &_num2, CommonAPI::CallStatus &_internalCallStatus, double &_result, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls add2 with asynchronous semantics.
     * 
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> add2Async(const double &_num1, const double &_num2, Add2AsyncCallback _callback, const CommonAPI::CallInfo *_info = nullptr);


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

 private:
    std::shared_ptr<sum_ifProxyBase> delegate_;
};

typedef sum_ifProxy<> sum_ifProxyDefault;


//
// sum_ifProxy Implementation
//
template <typename ... _AttributeExtensions>
sum_ifProxy<_AttributeExtensions...>::sum_ifProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast<sum_ifProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast<sum_ifProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
sum_ifProxy<_AttributeExtensions...>::~sum_ifProxy() {
}

template <typename ... _AttributeExtensions>
void sum_ifProxy<_AttributeExtensions...>::add2(const double &_num1, const double &_num2, CommonAPI::CallStatus &_internalCallStatus, double &_result, const CommonAPI::CallInfo *_info) {
    delegate_->add2(_num1, _num2, _internalCallStatus, _result, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> sum_ifProxy<_AttributeExtensions...>::add2Async(const double &_num1, const double &_num2, Add2AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->add2Async(_num1, _num2, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &sum_ifProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool sum_ifProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool sum_ifProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& sum_ifProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& sum_ifProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


} // namespace sum
} // namespace math
} // namespace v1_0


#endif // MATH_SUM_sum_if_PROXY_HPP_
