/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.3.v201507280808.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1_0/math/sum/sum_ifSomeIPDeployment.hpp>

namespace v1_0 {
namespace math {
namespace sum {
namespace sum_if_ {

// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployment

} // namespace sum_if_
} // namespace sum
} // namespace math
} // namespace v1_0
