/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.3.v201507280808.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef MATH_SUM_sum_if_STUB_HPP_
#define MATH_SUM_sum_if_STUB_HPP_

#include <functional>




#include <v1_0/math/sum/sum_if.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <vector>

#include <CommonAPI/Stub.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1_0 {
namespace math {
namespace sum {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service sum_if. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class sum_ifStubAdapter
    : virtual public CommonAPI::StubAdapter, 
      public sum_if {
 public:



    virtual void deactivateManagedInstances() = 0;
protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */
};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for sum_if.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class sum_ifStubRemoteEvent
{
public:
    virtual ~sum_ifStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service sum_if to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class sum_ifStub
    : public virtual CommonAPI::Stub<sum_ifStubAdapter, sum_ifStubRemoteEvent>
{
public:
    typedef std::function<void (double _result)>add2Reply_t;

    virtual ~sum_ifStub() {}
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> clientId) = 0;


    /// This is the method that will be called on remote calls on the method add2.
    virtual void add2(const std::shared_ptr<CommonAPI::ClientId> _client, double _num1, double _num2, add2Reply_t _reply) = 0;

    using CommonAPI::Stub<sum_ifStubAdapter, sum_ifStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<sum_ifStubAdapter, sum_ifStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<sum_ifStubAdapter, sum_ifStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef sum_ifStubRemoteEvent RemoteEventType;
    typedef sum_if StubInterface;
};

} // namespace sum
} // namespace math
} // namespace v1_0

#endif // MATH_SUM_sum_if_STUB_HPP_
