/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.3.v201507280808.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef IPC_MATH_add_api_STUB_DEFAULT_HPP_
#define IPC_MATH_add_api_STUB_DEFAULT_HPP_


#include <v1_0/ipc_math/add_apiStub.hpp>
#include <sstream>
#include <iostream>
#include <ctime>
#include <time.h>
#include <sys/time.h>

namespace v1_0 {
namespace ipc_math {

/**
 * Provides a default implementation for add_apiStubRemoteEvent and
 * add_apiStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class add_apiStubDefault
    : public virtual add_apiStub {
public:
    add_apiStubDefault();

    add_apiStubRemoteEvent* initStubAdapter(const std::shared_ptr<add_apiStubAdapter> &_adapter);

    const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client);


    virtual void add(const std::shared_ptr<CommonAPI::ClientId> _client, double _num1, double _num2, double _call_no, addReply_t _reply);



protected:
    class RemoteEventHandler: public virtual add_apiStubRemoteEvent {
    public:
        RemoteEventHandler(add_apiStubDefault *_defaultStub);


    private:
        add_apiStubDefault *defaultStub_;
    };
private:
    add_apiStubDefault::RemoteEventHandler remoteEventHandler_;


    CommonAPI::Version interfaceVersion_;
};

} // namespace ipc_math
} // namespace v1_0

#endif // IPC_MATH_add_api_STUB_DEFAULT
