/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.3.v201507280808.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/

#ifndef COMMONAPI_SOMEIP_ADD_API_DEPLOYMENT_HPP_
#define COMMONAPI_SOMEIP_ADD_API_DEPLOYMENT_HPP_



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif
#include <CommonAPI/SomeIP/Deployment.hpp>
#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1_0 {
namespace ipc_math {
namespace add_api_ {

// Interface-specific deployment types

// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployment

} // namespace add_api_
} // namespace ipc_math
} // namespace v1_0

#endif // COMMONAPI_SOMEIP_ADD_API_DEPLOYMENT_HPP_
